version: 1.0.{build}-{branch}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: x64
install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""
  
  - ps: mkdir C:\build | out-null
  - ps: mkdir C:\gdal | out-null
  
  - curl http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-2-1-3-mapserver-7-0-4-20170202.zip --output gdalbin.zip
  - 7z x gdalbin.zip -oC:\gdal
  - curl http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-2-1-3-mapserver-7-0-4-20170202-libs.zip --output gdallibs.zip  
  - 7z x gdallibs.zip -oC:\gdal
  - "SET PATH=C:\\gdal;C:\\gdal\\bin;C:\\gdal\\data;C:\\gdal\\bin\\gdal\\apps;%PATH%"
  - "SET GDAL_DATA=C:\\gdal\\bin\\gdal-data"

  - ECHO "Filesystem C:/GDAL:"
  - ps: "ls \"C:/GDAL\""
build:
  project: discretise-polygons.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - t.j.f.commandeur@tudelft.nl
  subject: Build new version of discretise-polygons
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false